Zookeeper fix
cisco-open/libnasp pull request #159
Opened 2023-04-04 13:45 UTC by baluchicken

## Description
Implements a couple of functions that were needed for the zookeeper client inside Kafka.
It contains a couple of bug fixes regarding accepting a connection.
Propagating DiscoveryClient to query the proper address of the instance.

## Type of Change

- [X] Bug Fix
- [X] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

2023-04-04 13:53 UTC, stoader submitted a review, later dismissed

2023-04-05 09:24 UTC, bonifaido commented on pkg/istio/tcp/dialer.go
> +		fmt.Println(err)
Some printouts are left here in this file, not sure if they are intentional, also this error handling is not correct I guess.

2023-04-05 09:26 UTC, baluchicken commented on pkg/istio/tcp/dialer.go
> +		fmt.Println(err)
Good catch was used for debugging.

2023-04-05 09:37 UTC, stoader requested changes

2023-04-05 09:37 UTC, stoader commented on experimental/java/examples/nio-java/src/main/java/com/ciscoopen/app/NaspSelectorProvider.java
>                  runningAsyncOps.put(selectedKeyId, runningOps | SelectionKey.OP_CONNECT);
Should this line move into the `if` block to ensure the `SelectionKey.OP_CONNECT` is added to the `runningOps` for `selectedKeyId` only when the async dial operation is started on the Go side.

2023-04-05 09:37 UTC, stoader commented on experimental/java/main.go
> +	if err != nil && !errors.Is(err, &ads.HostNotFoundError{HostName: address}) {
There is a `ads.IgnoreHostNotFound()` utility function that could be used here.

2023-04-05 09:37 UTC, stoader commented on experimental/java/examples/nio-java/src/main/java/com/ciscoopen/app/NaspSocketChannel.java
> +            naspTcpDialer.startAsyncDial(this.keyFor(selector).hashCode(), ((NaspSelector)selector).getSelector(),
Not sure if `runningOpts` should updated from here as well to avoid starting async dial go routine twice for the same selection key id. On the Go side we need also a protection similar to start async read/write to avoid starting the go routine twice for the same selection key id.

2023-04-11 13:26 UTC, baluchicken commented on experimental/java/examples/nio-java/src/main/java/com/ciscoopen/app/NaspSelectorProvider.java
>                  runningAsyncOps.put(selectedKeyId, runningOps | SelectionKey.OP_CONNECT);
No, in the [zkClient](https://github.com/apache/zookeeper/blob/3eda8a3a00ef3230d6c16f6ddf9201a3c0f5ca07/zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxnSocketNIO.java#L258) the registration happens before the connection. It means we do not have the address yet which is essential for the startAsyncDial function, but we got an event that we have to register otherwise it gets lost. So here we are registering the event and setting the selector for the naspSockerChannel so the next ZkClient [connect](https://github.com/apache/zookeeper/blob/3eda8a3a00ef3230d6c16f6ddf9201a3c0f5ca07/zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxnSocketNIO.java#L260) call can start the AsyncDial function.

2023-04-12 05:59 UTC, stoader approved these changes

2023-04-12 06:01 UTC, bonifaido approved these changes

2023-04-13 08:22 UTC, merged